### ISSUE TITLE
ERL-1477: Core dump at ethr_native_atomic64_add_return_mb

### ISSUE THREAD

**Issue by OTP-Maintainer** [erlang/otp#4459]
Original reporter: `JIRAUSER13002`
Affected version: `OTP-22.3`
Component: `erts`
Migrated from: https://bugs.erlang.org/browse/ERL-1477

---

```
OTP version is 22.3 erts-10.7

Program terminated with signal 11, Segmentation fault.

#0  0x00000000005a76d7 in ethr_native_atomic64_add_return_mb (incr=-1, var=0x7fc2d54c7eb6 <_L_unlock_713+23>) at ../include/internal/x86_64/../i386/atomic.h:240

240     ../include/internal/x86_64/../i386/atomic.h: No such file or directory.

Missing separate debuginfos, use: debuginfo-install glibc-2.17-222.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-18.el7.x86_64 libcom_err-1.42.9-11.el7.x86_64 libevent-2.0.21-4.el7.x86_64 libgcc-4.8.5-28.el7.x86_64 libselinux-2.5-12.el7.x86_64 libstdc++-4.8.5-28.el7.x86_64 ncurses-libs-5.9-14.20130511.el7_4.x86_64 openssl-libs-1.0.2k-12.el7.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-17.el7.x86_64

(gdb) backtrace

#0  0x00000000005a76d7 in ethr_native_atomic64_add_return_mb (incr=-1, var=0x7fc2d54c7eb6 <_L_unlock_713+23>) at ../include/internal/x86_64/../i386/atomic.h:240

#1  ethr_atomic_add_read (val=-1, var=0x7fc2d54c7eb6 <_L_unlock_713+23>) at ../include/internal/ethr_atomics.h:4219

#2  ethr_atomic_dec_read (var=0x7fc2d54c7eb6 <_L_unlock_713+23>) at ../include/internal/ethr_atomics.h:4806

#3  erts_refc_dectest (min_val=0, refcp=0x7fc2d54c7eb6 <_L_unlock_713+23>) at beam/sys.h:991

#4  erts_bin_release (bp=0x7fc2d54c7eae <_L_unlock_713+15>) at beam/erl_binary.h:510

#5  sweep_off_heap (p=p@entry=0x7fc291bc04d8, fullsweep=fullsweep@entry=1) at beam/erl_gc.c:2938

#6  0x00000000005aa762 in full_sweep_heaps (p=p@entry=0x7fc291bc04d8, live_hf_end=live_hf_end@entry=0xfffffffffffffff8, hibernate=hibernate@entry=0, n_heap=n_heap@entry=0x7fc0429b56f0, 

    n_htop=0x7fc0429b6e00, n_htop@entry=0x7fc0429b56f0, objv=objv@entry=0x7fc230ed1250, nobj=nobj@entry=5, oh_size=<optimized out>, oh=<optimized out>) at beam/erl_gc.c:1964

#7  0x00000000005ac2b3 in major_collection (recl=<synthetic pointer>, ygen_usage=<optimized out>, nobj=5, objv=0x7fc230ed1250, need=0, live_hf_end=0xfffffffffffffff8, p=0x7fc291bc04d8)

    at beam/erl_gc.c:1825

#8  garbage_collect (p=p@entry=0x7fc291bc04d8, live_hf_end=live_hf_end@entry=0xfffffffffffffff8, need=need@entry=0, objv=0x7fc230ed1250, nobj=5, fcalls=fcalls@entry=4000, 

    max_young_gen_usage=max_young_gen_usage@entry=0) at beam/erl_gc.c:775

#9  0x00000000005ad94b in erts_garbage_collect_nobump (p=p@entry=0x7fc291bc04d8, need=need@entry=0, objv=<optimized out>, nobj=<optimized out>, fcalls=4000) at beam/erl_gc.c:886

#10 0x00000000004675dc in scheduler_gc_proc (reds_left=4000, c_p=0x7fc291bc04d8) at beam/erl_process.c:9207

#11 erts_schedule (esdp=<optimized out>, p=0x7fc291bc04d8, calls=<optimized out>) at beam/erl_process.c:9932

#12 0x0000000000455cbd in process_main (x_reg_array=0x7fc293384280, f_reg_array=0x1) at beam/beam_emu.c:684

#13 0x000000000046dd3b in sched_thread_func (vesdp=0x7fc28a893540) at beam/erl_process.c:8498

#14 0x00000000006a941f in thr_wrapper (vtwd=<optimized out>) at pthread/ethread.c:118

#15 0x00007fc2d54c4dd5 in start_thread () from /lib64/libpthread.so.0

#16 0x00007fc2d4fe6b3d in clone () from /lib64/libc.so.6
```

**Comment by rickard-green** [comment]
Closing this since we have not got enough information to get further. Please open a new issue if/when you have more information.
