### ISSUE TITLE
TLS Certificate Unknown in OTP 24.3

### ISSUE THREAD

**Issue by hzeus** [erlang/otp#5835]
**Describe the bug**
After updating to OTP 24.3.2, we cannot establish an Elixir - HTTPoison connection to a server that requires a client certificate, instead we receive 

```elixir
{:error,
 %HTTPoison.Error{
   id: nil,
   reason: {:tls_alert,
    {:certificate_unknown,
     'TLS client: In state cipher received SERVER ALERT: Fatal - Certificate Unknown\n'}}
 }}
```

**To Reproduce**
Unfortunately this issues involves connecting to a private server of a partner that we cannot give access to; and we also do not have any access to the server in order to debug the requests. Please let me know about any debugging possibilities I should do to provide more information (see my attempts below)

**Expected behavior**
An established connection to the server.

**Affected versions**
(24.3,) 24.3.1 and 24.3.2, but not in 24.2.2

**Additional context**
When looking for an opportunity to debug the requests, I stumbled across `https://prod.idrix.eu/secure/`. I tested sending the requests against this server:

* OTP 24.2.2 worked as expected
* 24.3 returned `{:error, %HTTPoison.Error{id: nil, reason: :checkout_failure}}`
* 24.3.1 and 24.3.2 worked again (contrary to the server we are connecting to)

I then compared the outputs of requests of 24.2.2 and 24.3.2, and there are some whitespace related changes; however I do not know if is related in any way to the issue:

```diff
- [SSL_SECURE_RENEG] => true
+ [SSL_SECURE_RENEG] => true 

- [REQUEST_URI] => /secure/ 
+ [REQUEST_URI] => /secure/
```

Other differences are in `[SSL_SESSION_ID]`, `[REMOTE_PORT]`, `[REQUEST_TIME_FLOAT]` and `[REQUEST_TIME]`.

**Comment by IngelaAndin** [comment]
When the server asks for a client certificate it can include information about what certificate authorities it will accept and the client should select a certificate that adheres. Before we did not use this information, but now we do!

**Comment by IngelaAndin** [comment]
You could use option {log_level, debug}  to find out what the server expects.

**Comment by IngelaAndin** [comment]
I like to see the CertificateRequest message! That is the message that the server sends when it wants the client to send a certificate to verify itself. In this message, there can be information from the server that the client can possibly use to select a certificate that the server will be able to verify. The client may also send an "empty" certificate chain if it finds no suitable certificate. My guess is that it might be so that now when we process this information the client sends an "empty" certificate chain instead of the only certificate chain it has. The question then becomes what did the chain look like before and why could the server verify it in the same time it seems to claim it can not.

**Comment by hzeus** [comment]
This is the part that happens directly before the ClientKeyExchange I sent yesterday

**24.2.2**
```
[debug] [direction: :inbound, message: {:certificate_request, <<1, 2, 64>>, {:hash_sign_algos, [:rsa_pkcs1_sha256, :ecdsa_secp256r1_sha256, :rsa_pkcs1_sha384, :ecdsa_secp384r1_sha384, :rsa_pkcs1_sha512, :ecdsa_secp521r1_sha512]}, <<0, 187, 48, 129, 184, 49, 11, 48, 9, 6, 3, 85, 4, 6, 19, 2, 68, 69, 49, 20, 48, 18, 6, 3, 85, 4, 7, 12, 11, 68, 117, 101, 115, 115, 101, 108, 100, 111, 114, 102, 49, 12, 48, 10, ...>>}, protocol: :handshake]
reading (9 bytes) TLS 1.2 Record Protocol, handshake
0000 - 16 03 03 00 04 0e 00 00  00                         .........
[debug] [direction: :inbound, message: {:server_hello_done}, protocol: :handshake]
<<< Handshake, CertificateRequest
[{certificate_types,<<1,2,64>>},
 {hashsign_algorithms,
     {hash_sign_algos,
         [rsa_pkcs1_sha256,ecdsa_secp256r1_sha256,rsa_pkcs1_sha384,
          ecdsa_secp384r1_sha384,rsa_pkcs1_sha512,ecdsa_secp521r1_sha512]}},
 {certificate_authorities,
     <<0,187,48,129,184,49,11,48,9,6,3,85,4,6,19,2,68,69,49,20,48,18,6,3,85,
       [...]
       99,97,45,111,112,115,64,119,101,97,116,46,100,101>>}]
[debug] [direction: :outbound, message: {:certificate, [<<48, 130, 4, 102, 48, 130, 3, 78, 160, 3, 2, 1, 2, 2, 8, 76, 193, 158, 250, 181, 58, 113, 103, 48, 13, 6, 9, 42, 134, 72, 134, 247, 13, 1, 1, 11, 5, 0, 48, 129, 184, 49, 11, 48, 9, ...>>]}, protocol: :handshake]
<<< Handshake, ServerHelloDone
[]
>>> Handshake, Certificate
[{asn1_certificates,[<<48,130,4,102,48,130,3,78,160,3,2,1,2,2,8,76,193,158,
                      [...]
                       224,149,79,211,46,101,111>>]}]
[debug] [direction: :outbound, message: [<<22, 3, 3, 4, 116>>, <<11, 0, 4, 112, 0, 4, 109, 0, 4, 106, 48, 130, 4, 102, 48, 130, 3, 78, 160, 3, 2, 1, 2, 2, 8, 76, 193, 158, 250, 181, 58, 113, 103, 48, 13, 6, 9, 42, 134, 72, 134, 247, 13, 1, 1, 11, ...>>], protocol: :record]
writing (1145 bytes) TLS 1.2 Record Protocol, handshake
0000 - 16 03 03 04 74 0b 00 04  70 00 04 6d 00 04 6a 30    ....t...p..m..j0
0010 - 82 04 66 30 82 03 4e a0  03 02 01 02 02 08 4c c1    ..f0..N.......L.
[...]
0470 - f8 5d e0 95 4f d3 2e 65  6f                          .]..O..eo
[debug] [direction: :outbound, message: {:client_key_exchange, {:client_ec_diffie_hellman_public, <<4, 113, 34, 139, 190, 230, 140, 211, 175, 7, 210, 193, 185, 159, 246, 139, 238, 240, 209, 126, 70, 176, 37, 124, 23, 16, 225, 145, 133, 25, 207, 2, 181, 191, 75, 28, 199, 65, 89, 129, 231, 161, 194, 106, ...>>}}, protocol: :handshake]
[debug] [direction: :outbound, message: [<<22, 3, 3, 0, 70>>, <<16, 0, 0, 66, 65, 4, 113, 34, 139, 190, 230, 140, 211, 175, 7, 210, 193, 185, 159, 246, 139, 238, 240, 209, 126, 70, 176, 37, 124, 23, 16, 225, 145, 133, 25, 207, 2, 181, 191, 75, 28, 199, 65, 89, 129, 231, ...>>], protocol: :record]
>>> Handshake, ClientKeyExchange
```

**24.3.2**

```
[debug] [direction: :inbound, message: {:certificate_request, <<1, 2, 64>>, {:hash_sign_algos, [:rsa_pkcs1_sha256, :ecdsa_secp256r1_sha256, :rsa_pkcs1_sha384, :ecdsa_secp384r1_sha384, :rsa_pkcs1_sha512, :ecdsa_secp521r1_sha512]}, <<0, 187, 48, 129, 184, 49, 11, 48, 9, 6, 3, 85, 4, 6, 19, 2, 68, 69, 49, 20, 48, 18, 6, 3, 85, 4, 7, 12, 11, 68, 117, 101, 115, 115, 101, 108, 100, 111, 114, 102, 49, 12, 48, 10, ...>>}, protocol: :handshake]
<<< Handshake, CertificateRequest
[{certificate_types,<<1,2,64>>},
 {hashsign_algorithms,
     {hash_sign_algos,
         [rsa_pkcs1_sha256,ecdsa_secp256r1_sha256,rsa_pkcs1_sha384, 
          ecdsa_secp384r1_sha384,rsa_pkcs1_sha512,ecdsa_secp521r1_sha512]}},
 {certificate_authorities,
     <<0,187,48,129,184,49,11,48,9,6,3,85,4,6,19,2,68,69,49,20,48,18,6,3,85,
      [...]
       99,97,45,111,112,115,64,119,101,97,116,46,100,101>>}]
[debug] [direction: :inbound, message: {:server_hello_done}, protocol: :handshake]
<<< Handshake, ServerHelloDone
[]
[debug] [direction: :outbound, message: {:certificate, []}, protocol: :handshake]
>>> Handshake, Certificate
[{asn1_certificates,[]}]
[debug] [direction: :outbound, message: [<<22, 3, 3, 0, 7>>, <<11, 0, 0, 3, 0, 0, 0>>], protocol: :record]
writing (12 bytes) TLS 1.2 Record Protocol, handshake
0000 - 16 03 03 00 07 0b 00 00  03 00 00 00                ............
[debug] [direction: :outbound, message: {:client_key_exchange, {:client_ec_diffie_hellman_public, <<4, 21, 102, 56, 154, 243, 53, 116, 102, 119, 216, 73, 161, 74, 255, 249, 0, 33, 95, 174, 55, 142, 30, 178, 198, 0, 145, 45, 64, 119, 236, 181, 44, 82, 191, 23, 63, 14, 159, 179, 160, 247, 229, 58, ...>>}}, protocol: :handshake]
>>> Handshake, ClientKeyExchange
```

Please let me know if you need any more information. I removed some lines that contained some information about the certificat provider.

**Comment by IngelaAndin** [comment]
Has your client configured its chain certificats either by providing them with trustrd root certs in the cacert/cacertile option or by adding them after the own cert in the cert/certfile option? I suspect that if you if the answer is no we can not verify that your cert matches a cert that is verifiable by the server an an "empty" cert is sent instead. But as this kind of configuration error is common and the server may be able to recreate the chain and verify the cert which could explain why it worked before. I think in such a case it is two different parts of the protocol that kind of clashes. We could consider changing the default to sending the first certificte chain provided. Currently the only one, we will soon make it possible to have alternatives, if no alternative matches.

**Comment by hzeus** [comment]
We have received and tested a configuration with the root certificated, but still get the same error. 

The file has this structure:

```
-----BEGIN CERTIFICATE-----
(our certificate)
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
(the root certificate)
-----END CERTIFICATE-----
```

From what we can see via `openssl x509 -in <file> -text` the issuer of the root certificate contains the same value as the message that is sent from the server during `CertificateRequest`. 

Our currently used ssl options are `certfile`, `keyfile` and `password`, where `certfile` links to the new file.

**Comment by IngelaAndin** [comment]
Well if this is expected to help or not still depends.  We could start by inspecting your new file. 
```
{ok, Pem} = file:read_file("your_certfile.pem").

[{_, EntityCert, _}, {_, ROOTCert,_}] = public_key:pem_decode(Pem).

public_key:pkix_is_issuer(EnityCert, ROOTCert).
```
Will the last command return true?

**Comment by hzeus** [comment]
Thanks again for your help!

Yes, it does return true, this is the shell output I get (I removed some parts of the file contents)

```
➜  erl
Erlang/OTP 24 [erts-12.3] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]
Eshell V12.3  (abort with ^G)

1> {ok, Pem} = file:read_file("certificate.pem").
{ok,<<"-----BEGIN CERTIFICATE-----\nMIIEZjCCA06gAw"...>>}
2> [{_, EntityCert, _}, {_, ROOTCert,_}] = public_key:pem_decode(Pem).              
[{'Certificate',<<48,130,4,102...>>,
                not_encrypted},
 {'Certificate',<<48,130,4,...>>,
                not_encrypted}]
3> public_key:pkix_is_issuer(EntityCert, ROOTCert).                                 
true
```

**Comment by IngelaAndin** [comment]
Ok, so far so good. Let us try some tracing to try to figure out what is going on. 
Please check the results before posting so there is no information leakage. I will try to make traces that avoids it but hopefully gives us a clue.

So I want you to do the following commands from an erlang shell and then call ssl:connect with appropriate arguments.  
```

dbg:tracer(). 
dbg:p(all, [call]).
dbg:tpl(ssl_handshake, select_hashsign, cx).
dbg:tpl(ssl_certificate, handle_cert_auths, cx).

```

**Comment by hzeus** [comment]
This is the output I see:

```
(<0.699.0>) call ssl_handshake:select_hashsign({certificate_request,<<1,2,64>>,
                     {hash_sign_algos,[rsa_pkcs1_sha256,
                                       ecdsa_secp256r1_sha256,
                                       rsa_pkcs1_sha384,
                                       ecdsa_secp384r1_sha384,
                                       rsa_pkcs1_sha512,
                                       ecdsa_secp521r1_sha512]},
                     <<0,187,...>>},<<48,130,...>>,[ecdsa_secp521r1_sha512,ecdsa_secp384r1_sha384,ecdsa_secp256r1_sha256,
 rsa_pss_pss_sha512,rsa_pss_pss_sha384,rsa_pss_pss_sha256,rsa_pss_rsae_sha512,
 rsa_pss_rsae_sha384,rsa_pss_rsae_sha256,eddsa_ed25519,eddsa_ed448,
 {sha512,ecdsa},
 {sha512,rsa},
 {sha384,ecdsa},
 {sha384,rsa},
 {sha256,ecdsa},
 {sha256,rsa},
 {sha224,ecdsa},
 {sha224,rsa},
 {sha,ecdsa},
 {sha,rsa},
 {sha,dsa}],{3,3}) ({tls_dtls_connection,select_client_cert_key_pair,8})
(<0.699.0>) returned from ssl_handshake:select_hashsign/4 -> {alert,2,71,
                                                              #{file =>
                                                                 "ssl_handshake.erl",
                                                                line => 1693,
                                                                mfa =>
                                                                 {ssl_handshake,
                                                                  do_select_hashsign,
                                                                  3}},
                                                              undefined,
                                                              no_suitable_signature_algorithm}
[notice] TLS :client: In state :cipher received SERVER ALERT: Fatal - Certificate Unknown
```

One more thing that's in the output (sorry for not mentioning this before; I've somehow overseen this the whole time) is 

```
[warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'
```

which happens right before the call.

**Comment by IngelaAndin** [comment]
The warning is because you did not provide any truseted certs using the cacert/cacertfile options together with the {verify, verify_peer}  option, which means you can not verify the server certifcate chain.  So this means you will not have performed the authenicy check of the server. But it does not affect the client certification. 

Would you please also do public_key:pkix_decode_cert(EntityCert, otp).

**Comment by hzeus** [comment]
```
public_key:pkix_decode_cert(EntityCert, otp).
{'OTPCertificate',{'OTPTBSCertificate',v3,
                                       5530876617007198567,
                                       {'SignatureAlgorithm',{1,2,840,113549,1,1,11},'NULL'},
                                       {rdnSequence,[[{'AttributeTypeAndValue',{2,5,4,6},"DE"}],
                                                     [{'AttributeTypeAndValue',{2,5,4,7},
                                                                               {utf8String,<<"XXX">>}}],
                                                     [{'AttributeTypeAndValue',{2,5,4,8},{utf8String,<<"NRW">>}}],
                                                     [{'AttributeTypeAndValue',{2,5,4,10},
                                                                               {utf8String,<<"XXX">>}}],
                                                     [{'AttributeTypeAndValue',{2,5,4,11},
                                                                               {utf8String,<<"XXX">>}}],
                                                     [{'AttributeTypeAndValue',{2,5,4,3},
                                                                               {utf8String,<<"XXX">>}}],
                                                     [{'AttributeTypeAndValue',{1,2,840,113549,1,9,1},
                                                                               "xxx@xxx.de"}]]},
                                       {'Validity',{utcTime,"210121082300Z"},
                                                   {utcTime,"260121082300Z"}},
                                       {rdnSequence,[[{'AttributeTypeAndValue',{2,5,4,6},"DE"}],
                                                     [{'AttributeTypeAndValue',{2,5,4,8},
                                                                               {printableString,"NRW"}}],
                                                     [{'AttributeTypeAndValue',{2,5,4,7},
                                                                               {printableString,"XXX"}}],
                                                     [{'AttributeTypeAndValue',{2,5,4,10},
                                                                               {printableString,"XXX"}}],
                                                     [{'AttributeTypeAndValue',{2,5,4,11},
                                                                               {utf8String,<<"XXX">>}}],
                                                     [{'AttributeTypeAndValue',{2,5,4,3},
                                                                               {printableString,"xxx.de"}}],
                                                     [{'AttributeTypeAndValue',{1,2,840,113549,1,9,1},
                                                                               "xxx@xxx.de"}]]},
                                       {'OTPSubjectPublicKeyInfo',{'PublicKeyAlgorithm',{1,2,840,
                                                                                         113549,1,1,1},
                                                                                        'NULL'},
                                                                  {'RSAPublicKey',2333...}},
                                       asn1_NOVALUE,asn1_NOVALUE,
                                       [{'Extension',{2,5,29,14},
                                                     false,
                                                     <<185,253,64,225,49,181,158,232,221,81,41,...>>},
                                        {'Extension',{2,5,29,35},
                                                     false,
                                                     {'AuthorityKeyIdentifier',<<123,194,183,112,183,157,31,10,
                                                                                 ...>>,
                                                                               asn1_NOVALUE,asn1_NOVALUE}},
                                        {'Extension',{2,5,29,37},false,[{1,3,6,1,5,5,7,3,...}]},
                                        {'Extension',{2,5,29,17},
                                                     false,
                                                     [{iPAddress,<<x,x,x,x>>},
                                                      {iPAddress,<<x,x,x,x>>}]}]},
                  {'SignatureAlgorithm',{1,2,840,113549,1,1,11},'NULL'},
                  <<67,211,123,80,...>>}
```

**Comment by IngelaAndin** [comment]
Humm ... I am begining to suspect  conversion problems between TLS-1.3 and TLS-1.2 names.  Could you please make the traces:

dbg:tpl(ssl_handshake, is_supported_sign, cx).
dbg:tpl(ssl_handshake, do_select_hashsign, cx).

**Comment by hzeus** [comment]
```
(<0.699.0>) call ssl_handshake:is_supported_sign({sha256,rsa},'NULL',[rsa_pkcs1_sha256,ecdsa_secp256r1_sha256,rsa_pkcs1_sha384,
 ecdsa_secp384r1_sha384,rsa_pkcs1_sha512,ecdsa_secp521r1_sha512],[rsa_pkcs1_sha256,ecdsa_secp256r1_sha256,rsa_pkcs1_sha384,
 ecdsa_secp384r1_sha384,rsa_pkcs1_sha512,ecdsa_secp521r1_sha512]) ({ssl_handshake,
                                                                    select_hashsign,
                                                                    4})
(<0.699.0>) returned from ssl_handshake:is_supported_sign/4 -> true
(<0.699.0>) call ssl_handshake:do_select_hashsign([rsa_pkcs1_sha256,ecdsa_secp256r1_sha256,rsa_pkcs1_sha384,
 ecdsa_secp384r1_sha384,rsa_pkcs1_sha512,ecdsa_secp521r1_sha512],rsa,[ecdsa_secp521r1_sha512,ecdsa_secp384r1_sha384,ecdsa_secp256r1_sha256,
 rsa_pss_pss_sha512,rsa_pss_pss_sha384,rsa_pss_pss_sha256,rsa_pss_rsae_sha512,
 rsa_pss_rsae_sha384,rsa_pss_rsae_sha256,eddsa_ed25519,eddsa_ed448,
 {sha512,ecdsa},
 {sha512,rsa},
 {sha384,ecdsa},
 {sha384,rsa},
 {sha256,ecdsa},
 {sha256,rsa},
 {sha224,ecdsa},
 {sha224,rsa},
 {sha,ecdsa},
 {sha,rsa},
 {sha,dsa}]) ({tls_dtls_connection,select_client_cert_key_pair,8})
(<0.699.0>) returned from ssl_handshake:do_select_hashsign/3 -> {alert,2,71,
                                                                 #{file =>
                                                                    "ssl_handshake.erl",
                                                                   line =>
                                                                    1693,
                                                                   mfa =>
                                                                    {ssl_handshake,
                                                                     do_select_hashsign,
                                                                     3}},
                                                                 undefined,
                                                                 no_suitable_signature_algorithm}
```

**Comment by hzeus** [comment]
I ran into some issues when I tried this, here is what I came up with:

We are using Elixir, and when I switched to your PR I couldn't start the application with the error

```
Erlang/OTP 25 [RELEASE CANDIDATE 2] [erts-12.3.1] [source-af5e97c842] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

06:43:16.052 [error] beam/beam_load.c(86): Error loading module 'Elixir.Code.Formatter':
  lambda already defined for label 747. To fix this, please recompile this module with an OTP 25 compiler.

06:43:16.052 [error] Loading of /Users/heiko.zeus/.asdf/installs/elixir/1.13.3/bin/../lib/elixir/ebin/Elixir.Code.Formatter.beam failed: :badfile

** (UndefinedFunctionError) function Code.Formatter.locals_without_parens/0 is undefined (module Code.Formatter is not available)
    (elixir 1.13.3) Code.Formatter.locals_without_parens()
    (elixir 1.13.3) lib/code/normalizer.ex:22: Code.Normalizer.normalize/2
    (elixir 1.13.3) lib/code.ex:1107: Code.quoted_to_algebra/2
```

As a workaround, I forked OTP and copied the changes of your commit on the 24.3.3 tag, see https://github.com/hzeus/otp/commit/9690efbb101dcf853d7c086f5eaf6531fd6ae9a7). However, this did not solve the error and I still get the output

```
(<0.689.0>) call ssl_handshake:is_supported_sign({sha256,rsa},'NULL',[rsa_pkcs1_sha256,ecdsa_secp256r1_sha256,rsa_pkcs1_sha384,
 ecdsa_secp384r1_sha384,rsa_pkcs1_sha512,ecdsa_secp521r1_sha512],[rsa_pkcs1_sha256,ecdsa_secp256r1_sha256,rsa_pkcs1_sha384,
 ecdsa_secp384r1_sha384,rsa_pkcs1_sha512,ecdsa_secp521r1_sha512]) ({ssl_handshake,
                                                                    select_hashsign,
                                                                    4})
(<0.689.0>) returned from ssl_handshake:is_supported_sign/4 -> true
(<0.689.0>) call ssl_handshake:do_select_hashsign([rsa_pkcs1_sha256,ecdsa_secp256r1_sha256,rsa_pkcs1_sha384,
 ecdsa_secp384r1_sha384,rsa_pkcs1_sha512,ecdsa_secp521r1_sha512],rsa,[ecdsa_secp521r1_sha512,ecdsa_secp384r1_sha384,ecdsa_secp256r1_sha256,
 rsa_pss_pss_sha512,rsa_pss_pss_sha384,rsa_pss_pss_sha256,rsa_pss_rsae_sha512,
 rsa_pss_rsae_sha384,rsa_pss_rsae_sha256,eddsa_ed25519,eddsa_ed448,
 {sha512,ecdsa},
 {sha512,rsa},
 {sha384,ecdsa},
 {sha384,rsa},
 {sha256,ecdsa},
 {sha256,rsa},
 {sha224,ecdsa},
 {sha224,rsa},
 {sha,ecdsa},
 {sha,rsa},
 {sha,dsa}]) ({tls_dtls_connection,select_client_cert_key_pair,8})
(<0.689.0>) returned from ssl_handshake:do_select_hashsign/3 -> {alert,2,71,
                                                                 #{file =>
                                                                    "ssl_handshake.erl",
                                                                   line =>
                                                                    1703,
                                                                   mfa =>
                                                                    {ssl_handshake,
                                                                     do_select_hashsign,
                                                                     3}},
                                                                 undefined,
                                                                 no_suitable_signature_algorithm}
[notice] TLS :client: In state :cipher received SERVER ALERT: Fatal - Certificate Unknown
```

As an alternative approach, I tried to connect to the server in a pure Erlang shell, but I think I would need some guidance if I should follow this approach. When connecting to the server from a local machine, we also have to use a socks5 proxy (we set the `proxy`, `socks5_user` and `socks5_pass` options) - and I assume that we have to pass these options to ssl:connect as well, but I did not find out how.

My very first attempt would be

```erl
ssl:start().
ssl:connect("xxx.de", 40302, [{certfile, "certfile.pem"}, {keyfile, "keyfile.key"}, {password, "password"}], 1000).
```
which returns `{error, timeout}`.

**Comment by KennethL** [comment]
PR is corrected, please try it again

**Comment by hzeus** [comment]
I did, again with my OTP fork from 24.3.3 ([these are the changes that I copied from your commits](https://github.com/hzeus/otp/compare/OTP-24.3.3...hzeus:OTP-24.3.3-legacy-signature-names?expand=1)), and I now get the error 

```
[notice] TLS :client: In state :certify at tls_dtls_connection.erl:674 generated CLIENT ALERT: Fatal - Handshake Failure
 - :malformed_handshake_data
```

These are the outputs from the traces:

```
(<0.699.0>) call ssl_handshake:is_supported_sign({sha256,rsa},'NULL',[rsa_pkcs1_sha256,ecdsa_secp256r1_sha256,rsa_pkcs1_sha384,
 ecdsa_secp384r1_sha384,rsa_pkcs1_sha512,ecdsa_secp521r1_sha512],[rsa_pkcs1_sha256,ecdsa_secp256r1_sha256,rsa_pkcs1_sha384,
 ecdsa_secp384r1_sha384,rsa_pkcs1_sha512,ecdsa_secp521r1_sha512]) ({ssl_handshake,
                                                                    select_hashsign,
                                                                    4})
(<0.699.0>) returned from ssl_handshake:is_supported_sign/4 -> true
(<0.699.0>) call ssl_handshake:do_select_hashsign([rsa_pkcs1_sha256,ecdsa_secp256r1_sha256,rsa_pkcs1_sha384,
 ecdsa_secp384r1_sha384,rsa_pkcs1_sha512,ecdsa_secp521r1_sha512],rsa,[ecdsa_secp521r1_sha512,ecdsa_secp384r1_sha384,ecdsa_secp256r1_sha256,
 rsa_pss_pss_sha512,rsa_pss_pss_sha384,rsa_pss_pss_sha256,rsa_pss_rsae_sha512,
 rsa_pss_rsae_sha384,rsa_pss_rsae_sha256,eddsa_ed25519,eddsa_ed448,
 {sha512,ecdsa},
 {sha512,rsa},
 {sha384,ecdsa},
 {sha384,rsa},
 {sha256,ecdsa},
 {sha256,rsa},
 {sha224,ecdsa},
 {sha224,rsa},
 {sha,ecdsa},
 {sha,rsa},
 {sha,dsa}]) ({tls_dtls_connection,select_client_cert_key_pair,8})
(<0.699.0>) returned from ssl_handshake:do_select_hashsign/3 -> rsa_pkcs1_sha256
```

**Comment by hzeus** [comment]
Is there anything I can do to help with this issue at this moment?

**Comment by garazdawi** [comment]
> Is there anything I can do to help with this issue at this moment?

As it is currently Easter holidays here in Sweden things will be a bit slower this and next week. We will get back to you as soon as possible.

**Comment by hzeus** [comment]
Thanks for the answer, and have a nice holiday!

**Comment by IngelaAndin** [comment]
Updated the PR, see also comment in PR.

**Comment by hzeus** [comment]
This seems to work, thank you very much! 🎉 

I [copied the changes to my repo again](https://github.com/hzeus/otp/compare/OTP-24.3.3...hzeus:OTP-24.3.3-legacy-signature-names?expand=1) and could then perform a successful request. Looking forward to the next release.

**Comment by IngelaAndin** [comment]
@hzeus I am glad it works, however, I would like to be able to create our own test case for this. I am also still a little puzzled about how the code actually ends up in this state.
Could you  make another trace where you trace the  function  
`dbg:tpl(ssl_handshake, decode_sign_alg, cx).`  and share the results ?

Also do you know which ssl the server you connect to happens to use?

**Comment by hzeus** [comment]
Trace Output:

```
(<0.16050.0>) call ssl_handshake:decode_sign_alg({3,4},<<4,1,4,3,5,1,5,3,6,1,6,3>>) ({ssl_handshake,
                                                                                      decode_handshake,
                                                                                      3})
(<0.16050.0>) returned from ssl_handshake:decode_sign_alg/2 -> [rsa_pkcs1_sha256,
                                                                ecdsa_secp256r1_sha256,
                                                                rsa_pkcs1_sha384,
                                                                ecdsa_secp384r1_sha384,
                                                                rsa_pkcs1_sha512,
```

Regarding the SSL Version: I find the following lines in the debug output when I grep for TLS

```
>>> TLS 1.3 Handshake, ClientHello
<<< TLS 1.2 Handshake, ServerHello
reading (2333 bytes) TLS 1.2 Record Protocol, handshake
(...)
```

Does this answer your question or do you mean something else?

**Comment by IngelaAndin** [comment]
Well the thing that is bothering me is that the client calls this function when decoding the certificate_request message from the server when we have negotiated TLS-1.2 and 
hence the call ought to have been 

`ssl_handshake:decode_sign_alg({3,3},<<4,1,4,3,5,1,5,3,6,1,6,3>>)`

and then my fixes should not have been needed.  TLS-1.2 (3,3) TLS-1.3 (3,4) 
So I think I will investigate this further.

**Comment by IngelaAndin** [comment]
I was interested in whether the server was running OpenSSL, java SSL solution, GnuTLS, LibreSSL, or other SSL solutions. But I do not think it matters, I think the problem is with our client.

**Comment by IngelaAndin** [comment]
@hzeus  Could you please try the new PR  #5919 instead!  I think it is the correct "TM" fix. And with the assertion for TLS-1.2 (instead of test for at least TLS-1.2) that I added I think it is enough that now existing tests are failing.

**Comment by hzeus** [comment]
This looks good as well 👍 

For reference: I again copied your changes to OTP-24.3.3, see [the cherry-picked commit](https://github.com/erlang/otp/compare/OTP-24.3.3...hzeus:OTP-24.3.3-decode-cert-request-algs?expand=1)
